[package]
name = "mighty_mule_gate"
version = "0.1.0"
authors = ["Myles Empty Best <myles@empty.best>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]